name: PR Build
on:
  pull_request:
    paths-ignore:
    - '**.md'
env:
  REALM_DISABLE_ANALYTICS: true
jobs:
  # TODO Should be working, disable while iterating on further steps to increase turn-around time. 
  # static-analysis:
  #   uses: ./.github/workflows/include-static-analysis.yml

  # Check if we actually need to build any of the packages. This is done by hashing all
  # source files and use that as part of the version name, i.e. `1.0.0-fbc7df86ef5a8694873c863f9e30fb1e147efa54`.
  check-cache:
    runs-on: ubuntu-latest
    name: Check cache 
    env:
      CACHE_SKIP_SAVE: true
    outputs:  
      packages-linux-cache-hit: ${{ steps.calculate-cache-exists.outputs.cache-hit }}
      packages-linux-sha: ${{ steps.calculate-packages-cache-key.outputs.sha }}
      benchmarks-lin-sha: ${{ steps.calculate-benchmarks-cache-key.outputs.sha }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: "recursive"

    - name: Calculate ./packages SHAs 
      id: calculate-packages-cache-key
      run: echo "::set-output name=sha::${{ hashFiles('./packages/**') }}"  

    - name: Calculate ./benchmarks SHAs 
      id: calculate-benchmarks-cache-key
      run: echo "::set-output name=sha::${{ hashFiles('./packages/**') }}"  

    # TODO There doesn't seem to be a good way to check if a cache key exists without download it.
    # https://github.com/actions/cache/issues/321
    # TODO Create a custom action for this until we have a work-around?
    # Name of key must match output of `Store build artifacts`.
    - name: Calculate cache exists 
      id: calculate-cache-exists
      uses: nirinchev/cache@d7c96a77c26ab70dd32b202c885cb4b34d95d8a8
      with:
        path: ./packages/build/m2-buildrepo
        key: packages-m2-${{ runner.os }}-sync-${{ steps.calculate-cache-key.outputs.packages-sha }}

  build-packages:
    runs-on: ubuntu-latest
    needs: check-cache
    # needs: static-analysis
    if: needs.check-cache.outputs.packages-linux-cache-hit != 'true'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - uses: ./.github/actions/setup-build-dependencies    


      - name: Build packages
        working-directory: packages
        run: ./gradlew publishCIPackages --info

      # TODO Figure out naming schema and retention policy
      # We cannot use artifacts as they cannot be shared between workflows, so use cache instead.
      - name: Store build artifacts
        uses: actions/cache@v3
        with:
          path: ./packages/build/m2-buildrepo
          key: packages-m2-${{ runner.os }}-sync-${{ needs.check-cache.outputs.packages-linux-sha }}
 
  build-benchmarks:
    runs-on: ubuntu-latest
    needs: check-cache
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-build-dependencies    
  
  test-packages:
    runs-on: ubuntu-latest
    needs: [check-cache, build-packages]
    if: |
      always() &&
      (needs.build-packages.result == 'success' || needs.build-packages.result == 'skipped')

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: Restore m2-buildrepo
        uses: actions/cache@v3
        with:
          path: ./packages/build/m2-buildrepo
          key: packages-m2-${{ runner.os }}-sync-${{ needs.check-cache.outputs.packages-linux-sha }}

      - name: Run tests
        run: echo "Run tests for ${{ needs.check-cache.outputs.packages-linux-sha }}"
